meta_product_name: "The Home Chef"
meta_title: "The Home Chef - Book a Cook!"
meta_description: "Enjoy homemade fresh meals at home on a weekly basis, cooked by passionate people who want to share their best recipes."
meta_image: "http://res.cloudinary.com/lucien-andrieux/image/upload/v1606232563/pbfh3pvwgpn1gepsnahw.png" # should exist in `app/assets/images/`
